# docker-compose.yml
version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: db-mysql-con
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    networks:
      - db-mysql-net

  adminer:
    image: adminer
    container_name: adminer-con
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db-mysql-net

  mongodb:
    image: mongo:latest
    container_name: db-mongodb-con
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb-data:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - db-mongodb-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
    networks:
      - db-mongodb-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-con
    restart: always
    ports:
      - "9411:9411"
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - db-redis-net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-con
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - rabbitmq-net

  service-registry:
    image: laminhtam/service-registry:latest
    ports:
      - "8761:8761"
    networks:
      - backend

  config-server:
    image: laminhtam/config-server:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - ./UniEnrollSystemBE/config-server:/config
    networks:
      - backend

  gateway:
    image: laminhtam/gateway:latest
    restart: always
    ports:
      - "8060:8060"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    volumes:
      - ./UniEnrollSystemBE/api-gateway:/config
    networks:
      - backend
    depends_on:
      - service-registry
      - config-server

  auth-service:
    image: laminhtam/auth-service:latest
    restart: always
    ports:
      - "9004:9004"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_APPLICATION_NAME=auth-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - JWT_SECRET=4d5a23bd0646523b4aaae7a51a92a62babcb4eb353843a3fa4ef4ef05f534a68
      - JWT_EXPIRATION=86400
    volumes:
      - ./UniEnrollSystemBE/auth-service:/config
    depends_on:
      - service-registry
      - config-server
      - gateway
      - mysql
    networks:
      - backend
      - db-mysql-net

  faculty-service:
    image: laminhtam/faculty-service:latest
    restart: always
    ports:
      - "8082:8082"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_APPLICATION_NAME=faculty-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/faculty_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    depends_on:
      - service-registry
      - config-server
      - gateway
      - mysql
    volumes:
      - ./UniEnrollSystemBE/faculty-service:/config
    networks:
      - backend
      - db-mysql-net

  course-service:
    image: laminhtam/course-service:latest
    restart: always
    ports:
      - "8086:8086"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_APPLICATION_NAME=course-service
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=db-mongodb-con
      - SPRING_DATA_MONGODB_DATABASE=course_db
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_URI=mongodb://root:123456@mongodb:27017/admin
    volumes:
      - ./UniEnrollSystemBE/course-service:/config
    depends_on:
      - service-registry
      - config-server
      - gateway
      - mongodb
    networks:
      - backend
      - db-mongodb-net

  enroll-service:
    image: laminhtam/enroll-service:latest
    restart: always
    ports:
      - "8084:8084"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_APPLICATION_NAME=enroll-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/enroll_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_DATA_REDIS_DATABASE=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUT=60000
      - SPRING_DATA_REDIS_PASSWORD=123456
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    volumes:
      - ./UniEnrollSystemBE/enroll-service:/config
    depends_on:
      - service-registry
      - config-server
      - gateway
      - mysql
      - redis
      - rabbitmq
    networks:
      - backend
      - db-mysql-net
      - db-redis-net
      - rabbitmq-net

  schedule-service:
    image: laminhtam/schedule-service:latest
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=db-mongodb-con
      - SPRING_DATA_MONGODB_DATABASE=schedule_db
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_URI=mongodb://root:123456@mongodb:27017/admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
      - config-server
      - mongodb
      - gateway
      - redis
      - rabbitmq
    networks:
      - backend
      - db-mongodb-net
      - db-redis-net
      - rabbitmq-net

  grade-management-service:
    image: laminhtam/grade-management-service:latest
    restart: always
    ports:
      - "8087:8087"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=db-mongodb-con
      - SPRING_DATA_MONGODB_DATABASE=grade_db
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_URI=mongodb://root:123456@mongodb:27017/admin
    volumes:
      - ./UniEnrollSystemBE/grade-management-service:/config
    depends_on:
      - service-registry
      - config-server
      - gateway
      - mongodb
    networks:
      - backend
      - db-mongodb-net

  payment-service:
    image: laminhtam/payment-service:latest
    restart: always
    ports:
      - "8089:8089"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=db-mongodb-con
      - SPRING_DATA_MONGODB_DATABASE=payment_db
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_URI=mongodb://root:123456@mongodb:27017/admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    depends_on:
      - service-registry
      - config-server
      - mongodb
      - gateway
      - rabbitmq
      - schedule-service
    networks:
      - backend
      - db-mongodb-net
      - rabbitmq-net

volumes:
  mysql-data:
  mongodb-data:

networks:
  db-mysql-net:
  db-mongodb-net:
  backend:
  db-redis-net:
  rabbitmq-net:
