# docker-compose.yml
version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: db-mysql-con
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
    networks:
      - db-mysql-net
      - db-mongodb-net

  adminer:
    image: adminer
    container_name: adminer-con
    restart: always
    ports:
      - "8080:8080"
    networks:
      - db-mysql-net
      - db-mongodb-net

  mongodb:
    image: mongo:latest
    container_name: db-mongodb-con
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb-data:/data/db
    networks:
      - db-mongodb-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
    networks:
      - db-mongodb-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-con
    restart: always
    ports:
      - "9411:9411"
    networks:
      - db-mysql-net
      - db-mongodb-net

  # service-registry:
  #   build: ./UniEnrollSystemBE/service-registry
  #   restart: always
  #   ports:
  #     - "8761:8761"
  #   networks:
  #     - db-mysql-net
  #     - db-mongodb-net
  
  # config-server:
  #   build: ./UniEnrollSystemBE/config-server
  #   restart: always
  #   ports:
  #     - "8088:8088"
  #   networks:
  #     - db-mysql-net
  #     - db-mongodb-net
  #   depends_on:
  #     - service-registry

  # enroll-service:
  #   build: ./UniEnrollSystemBE/enroll-service
  #   restart: always
  #   ports:
  #     - "8084:8084"
  #   networks:
  #     - db-mysql-net
  #     - db-mongodb-net
  #   depends_on:
  #     - service-registry
  #     - config-server

  # auth-service:
  #   build: ./UniEnrollSystemBE/auth-service
  #   restart: always
  #   ports:
  #     - "9004:9004"
  #   networks:
  #     - db-mysql-net
  #     - db-mongodb-net
  #   depends_on:
  #     - service-registry
  #     - config-server

  # faculty-service:
  #   build: ./UniEnrollSystemBE/faculty-service
  #   restart: always
  #   ports:
  #     - "8082:8082"
  #   networks:
  #     - db-mysql-net
  #     - db-mongodb-net
  #   depends_on:
  #     - service-registry
  #     - config-server

  # gateway:
  #   build: ./UniEnrollSystemBE/api-gateway
  #   restart: always
  #   ports:
  #     - "8060:8060"
  #   depends_on:
  #     - enroll-service

volumes:
  mysql-data:
  mongodb-data:

networks:
  db-mysql-net:
  db-mongodb-net:
