FROM openjdk:17-oracle
COPY ./target/grade-management-service-0.0.1-SNAPSHOT.jar grade-management-service-0.0.1-SNAPSHOT.jar
EXPOSE 8087
CMD ["java", "-jar", "grade-management-service-0.0.1-SNAPSHOT.jar"]