server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  data:
    mongodb:
      port: 27017
      host: localhost
      database: payment_db
      authentication-database: admin
      uri: mongodb://root:123456@localhost:27017/admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
prices: 1_2021-1000_2000,
  2_2021-1000_2000,
  1_2022-1100_2100,
  2_2022-1100_2100,
  1_2023-1200_2200,
  2_2023-1200_2200,
  1_2024-1300_2300,
  2_2024-1300_2300
vnp:
  secretKey: ${VNP_SECRET_KEY:HF34SXY0OXR4ZWMIHHO4HRHMC7F9R1II}
  version: ${VNP_VERSION:2.1.0}
  vnp_TmnCode: ${VNP_TMN:IAKOY4KK}
  vnp_Url: ${VNP_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  vnp_ReturnUrl: ${VNP_RETURN_URL:http://localhost:8099/vnpay_jsp/vnpay_return.jsp}
  vnp_ApiUrl: ${VNP_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}
  vnp_Command: ${VNP_COMMAND:pay}
