spring:
  application:
    name: schedule-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      port: 27017
      host: localhost
      database: schedule_db
      authentication-database: admin
      uri: mongodb://root:123456@localhost:27017/admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456