server:
  port: 8060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
#        - id: student-service
#          uri: lb://student-service
#          predicates:
#            - Path=/student/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: faculty-service
          uri: lb://faculty-service
          predicates:
            - Path=/faculties/**
            - Path=/students/**
            - Path=/courses/**
  main:
    web-application-type: reactive

jwt:
  secret: 4d5a23bd0646523b4aaae7a51a92a62babcb4eb353843a3fa4ef4ef05f534a68